### PR TITLE
Add Rx2 and submodule

### PR DESCRIPTION
**Pull request by hoanghiephui**

### CODE REVIEW

**Comment by tspoke** [comment]
Thank you for this ;)
I will do the same that I did for store2store and create a rxjava2 branch to merge this PR into for now. 
I will test it asap and merge it in master in a second time ! 

Did you test the lib in a project ? Or did you only migrate the code ?

I don't think I will keep the git submodule you added, I prefer the gradle dependency personally. What do you think ?

**Comment by hoanghiephui** [comment]
OK, I also think like you, I use the submodule is to support me editing. I have not test it yet, it's still not working properly. If possible, please help me. Thanks

**Comment by tspoke** [comment]
Ok ! I will test it as soon as possible on the rxjava2 branch. I will push an example project into the repository. Give me some time :)

**Comment by hoanghiephui** [comment]
Like like 💯

**Comment by tspoke** [comment]
I just add a working example in the rxjava2 branch. Your code was not working due to some issues (fixed), so now it should be good with the store2store rxjava2 too !

**Pull request merged**
